
INC_DIR += $(PROJDIR)/app
INC_DIR += $(PROJDIR)/base
INC_DIR += $(PROJDIR)/base/util
INC_DIR += $(PROJDIR)/bin
INC_DIR += $(PROJDIR)/http
INC_DIR += $(PROJDIR)/dns

SRC_DIR += $(PROJDIR)/base/util
SRC_DIR += $(PROJDIR)/base
SRC_DIR += $(PROJDIR)/http
SRC_DIR += $(PROJDIR)/dns
SRC_DIR += $(PROJDIR)/app

include $(PROJDIR)/build.mk

all:lib
