
SRC_DIR += $(PROJDIR)/base/util
SRC_DIR += $(PROJDIR)/base
SRC_DIR += $(PROJDIR)/http
SRC_DIR += $(PROJDIR)/dns

INC_DIR += $(PROJDIR)/base/util
INC_DIR += $(PROJDIR)/base
INC_DIR += $(PROJDIR)/dns
INC_DIR += $(PROJDIR)/http
INC_DIR += $(PROJDIR)/app

include $(PROJDIR)/build.mk


