
SRC_DIR += $(PROJDIR)/base/util
SRC_DIR += $(PROJDIR)/base
SRC_DIR += $(PROJDIR)/http

INC_DIR += $(PROJDIR)/app
INC_DIR += $(PROJDIR)/base
INC_DIR += $(PROJDIR)/http
INC_DIR += $(PROJDIR)/base/util

include $(PROJDIR)/build.mk


all:lib
