
SRC_DIR += $(PROJDIR)/base/util

INC_DIR += $(PROJDIR)/base/util
INC_DIR += $(PROJDIR)/base
INC_DIR	+= $(PROJDIR)/lib/include
INC_DIR += $(PROJDIR)/lib/crypto


include $(PROJDIR)/build.mk

all:lib


