
INC_DIR += $(PROJDIR)/base/util
INC_DIR += $(PROJDIR)/base
INC_DIR += $(PROJDIR)/bin
INC_DIR += $(PROJDIR)/dns
INC_DIR += $(PROJDIR)/app
INC_DIR += $(PROJDIR)/http

SRC_DIR += $(PROJDIR)/base/util

include $(PROJDIR)/build.mk

all:lib
